# Generated by Django 5.1.6 on 2025-02-13 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_share_post_alter_share_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='save',
            unique_together={('user', 'post')},
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
